### ISSUE TITLE
New User is unable to query data from /api/v1/dashboard

### ISSUE THREAD

**Issue by andrewzlchen** [stevens-tyr/backend#24]
When creating a new user from "Sign up" Page, this new user sees nothing on the Dashboard. 

**View from Frontend:**

We get a 500 error..
![image](https://user-images.githubusercontent.com/15252988/55363157-2b59f500-54aa-11e9-921f-5c1d37b2deec.png)

**View from Backend:**

It appears that when we GET /api/v1/dashboard, we're running some kind of code that results in an "Invalid BSON Object" Error.
![image](https://user-images.githubusercontent.com/15252988/55363182-3d3b9800-54aa-11e9-9650-f1de49fa87be.png)

I suspect that we're not accounting for new users that have no courses associated with them and therefore, we get this error.

**Steps to Reproduce Error:**

1. Start frontend dev server
2. Go to http://localhost:3000/signup
3. Create a new user
4. Go to Dashboard
5. You should see an empty screen dashboard
![image](https://user-images.githubusercontent.com/15252988/55363336-bc30d080-54aa-11e9-8246-a595a68096ca.png)

**Comment by gluax** [comment]
@robherley Can you replicate this error? I can not seem to do so...

**Comment by andrewzlchen** [comment]
Solved. I previous had an older mongo v3 version. After upgrading to v4, I got it to work.
